### ISSUE TITLE
时间后面加上秒就更香了

### ISSUE THREAD

**Issue by wlc743859910** [imsyy/Snavigation#1]
如题

**Comment by imsyy** [comment]
可以参考这里改成按秒显示
https://github.com/imsyy/home/blob/bd4ad30524ab37754d1e1f0f00bddb2cbb6d4efd/js/main.js#L108

**Comment by wlc743859910** [comment]
> [可以参考这里改成秒显示按https://github.com/imsyy/home/blob/bd4ad30524ab37754d1e1f0f00bddb2cbb](https://github.com/imsyy/home/blob/bd4ad30524ab37754d1e1f0f00bddb2cbb6d4efd/js/main.js#L108)​​ 6d4efd/js/main.js#L108 [](https://github.com/imsyy/home/blob/bd4ad30524ab37754d1e1f0f00bddb2cbb6d4efd/js/main.js#L108)

好的喔
