### ISSUE TITLE
可以加入duckduckgo搜索引擎吗 还有就是没有快捷导航吗 看演示站没有诶

### ISSUE THREAD

**Issue by Yakumo-Yukari** [imsyy/Snavigation#14]

**Comment by Yakumo-Yukari** [comment]
好吧 快捷导航看到了  需要点击时间哪里  ，建议加入提示 如果是第一次使用 根本就不会想到快捷导航在那里

**Comment by imsyy** [comment]
> 好吧 快捷导航看到了 需要点击时间哪里 ，建议加入提示 如果是第一次使用 根本就不会想到快捷导航在那里

嗯，这个提示可以加上，另外搜索引擎是可以自定义的 🤪
