### ISSUE TITLE
作者你好，你的Made by版权信息已被某人篡改为他自己

### ISSUE THREAD

**Issue by damengzhu** [imsyy/Snavigation#19]
https://github.com/xiaohao8/Snavigation/blob/master/index.html

![Screenshot_20230608183304](https://github.com/imsyy/Snavigation/assets/80020206/5196885f-10a2-41da-8ab2-3563a74d7f3f)

**Comment by damengzhu** [comment]
![Uploading Screenshot_2023-06-08-18-31-12-219_com.coolapk.market.jpeg…]()

**Comment by damengzhu** [comment]
![Screenshot_20230608184017](https://github.com/imsyy/Snavigation/assets/80020206/29c4cc34-d684-42b7-9c88-31ff16727efe)
![Screenshot_20230608184030](https://github.com/imsyy/Snavigation/assets/80020206/691a63ec-b0da-4951-875c-b7fbaf9cc69e)
![Screenshot_20230608184034](https://github.com/imsyy/Snavigation/assets/80020206/5c71688e-6d9a-42bc-886c-ba29ea5ad90c)
![Screenshot_20230608184038](https://github.com/imsyy/Snavigation/assets/80020206/d738db12-8647-4598-95b0-f9650100d129)
![Screenshot_20230608184042](https://github.com/imsyy/Snavigation/assets/80020206/18fdea9d-186c-4de8-b024-818621a585e7)
![Screenshot_20230608184049](https://github.com/imsyy/Snavigation/assets/80020206/6f124da7-d82d-4911-8baf-45bd89a0c3d5)
![Uploading Screenshot_20230608184054.png…]()

**Comment by damengzhu** [comment]
![Uploading Screenshot_20230608184054.png…]()

**Comment by damengzhu** [comment]
![Screenshot_20230608184054](https://github.com/imsyy/Snavigation/assets/80020206/a1a39864-8709-42da-bcf4-5838a257686b)

**Comment by imsyy** [comment]
没事的，不用争论了，我这好久以前的项目了，想着有空了重构一下呢 😂，代码就随便改吧，无所谓的 👻
