### ISSUE TITLE
搜索框的联想词无法点击

### ISSUE THREAD

**Issue by ikenliao** [imsyy/Snavigation#2]
如题，搜索框可以根据输入的词汇进行联想，但联想的词无法点击，一点击搜索信息就会丢失，回到空白搜索框的状态

**Comment by imsyy** [comment]
项目现在还有很多问题，等我有空了试着修修 😂

**Comment by ikenliao** [comment]
感觉除了这个搜索框，已经很完美了
![2A6FD1D1](https://user-images.githubusercontent.com/50474986/185310580-6eddc475-7930-4340-ac0b-0064543813b5.png)

**Comment by imsyy** [comment]
这不就是最大的问题嘛 🤣
