### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by orangbus** [imsyy/Snavigation#20]
可以在搜索栏下面添加6-8个常用的地址快捷方式，类似google的主页一样的，点击更多的时候背景虚化，弹出所有的快捷地址。
第一次遇到一个设计风格跟我想要的是一致的，加油

**Comment by imsyy** [comment]
收到，近期会开始重构

**Comment by xiaomailang** [comment]
真的重构吗，太棒了！上面的建议也很不错，添加几个常用高频的地址快捷方式，但建议加个开关，有需要的开，不需要的关，不影响整个主页简洁。功能上能不能实现一个备忘录功能

**Comment by imsyy** [comment]
> 真的重构吗，太棒了！上面的建议也很不错，添加几个常用高频的地址快捷方式，但建议加个开关，有需要的开，不需要的关，不影响整个主页简洁。功能上能不能实现一个备忘录功能

ok 👌
