### ISSUE TITLE
关于自定义壁纸链接

### ISSUE THREAD

**Issue by Kirara-Tianqing** [imsyy/Snavigation#30]
我在自家nas上搭建了自用的壁纸库，因为家用宽带封80和443端口的原因所以访问时用的别的端口，这就导致了导航里面我使用自己的壁纸库报错，这个壁纸链接的识别是不是可以优化下：
![image](https://github.com/imsyy/Snavigation/assets/81161427/fe6fe9c5-4410-409f-880f-e661fa84a95a)

**Comment by ht0222** [comment]
直接去后台改默认链接，把动漫和风景的链接直接替换成你自己的就好

天青 ***@***.***> 于2023年11月24日周五 08:09写道：

**Comment by imsyy** [comment]
@FengmiQingmei 已修复

**Comment by Kirara-Tianqing** [comment]
感谢大佬
